// CALENDAR
// ────────────────────────────────────────
function initCal(){var d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();buildCPicker();renderCal()}
function buildCPicker(){document.getElementById('colorPicker').innerHTML=ECOLS.map(function(c,i){return'<div class="cpick'+(i===S.evColor?' on':'')+'" style="background:'+c+'" onclick="pickColor('+i+')" title="'+ECLBL[i]+'"></div>';}).join('');}
function pickColor(i){S.evColor=i;document.querySelectorAll('.cpick').forEach(function(c,ci){c.classList.toggle('on',ci===i)})}
function calMove(d){S.calM+=d;if(S.calM>11){S.calM=0;S.calY++}if(S.calM<0){S.calM=11;S.calY--}renderCal()}
function calToday(){var d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();renderCal()}
function setCalView(v,el){S.calView=v;document.querySelectorAll('.cal-vbtn').forEach(function(b){b.classList.remove('on')});el.classList.add('on');renderCal()}
function dStr(y,m,d){return y+'-'+p2(m+1)+'-'+p2(d)}
function evsOn(ds){return S.events.filter(function(e){return e.date===ds})}
function renderCal(){var now=new Date();var todStr=dStr(now.getFullYear(),now.getMonth(),now.getDate());document.getElementById('calTitle').textContent=S.calY+'年'+(S.calM+1)+'月';document.getElementById('calBody').innerHTML=S.calView==='month'?buildMonthCal(todStr):buildWeekCal(todStr);}
function buildMonthCal(todStr){var DOW=['日','月','火','水','木','金','土'];var first=new Date(S.calY,S.calM,1);var dow=first.getDay();var dim=new Date(S.calY,S.calM+1,0).getDate();var dip=new Date(S.calY,S.calM,0).getDate();var h='<div class="cal-grid">';DOW.forEach(function(d){h+='<div class="cal-dow">'+d+'</div>'});for(var i=dow-1;i>=0;i--)h+='<div class="cal-cell other"><div class="cal-dn">'+(dip-i)+'</div></div>';for(var d=1;d<=dim;d++){var ds=dStr(S.calY,S.calM,d);var isT=ds===todStr;var evs=evsOn(ds);var eh=evs.slice(0,3).map(function(e){return'<div class="cal-ev ec'+e.color+'" onclick="openCalEv(\''+e.id+'\',event)">'+esc(e.start?e.start+' ':'')+esc(e.title)+'</div>';}).join('');if(evs.length>3)eh+='<div style="font-family:var(--mono);font-size:.52rem;color:var(--txD)">+'+(evs.length-3)+' more</div>';h+='<div class="cal-cell'+(isT?' today':'')+(ds<todStr&&!isT?' other':'')+'" onclick="openNewEv(\''+ds+'\',event)"><div class="cal-dn">'+d+'</div>'+eh+'</div>';}var tot=dow+dim;var rem=(7-tot%7)%7;for(var n=1;n<=rem;n++)h+='<div class="cal-cell other"><div class="cal-dn">'+n+'</div></div>';return h+'</div>';}
function buildWeekCal(todStr){var now=new Date();var ws=new Date(now);ws.setDate(now.getDate()-now.getDay());var cols=[];for(var i=0;i<7;i++){var dd=new Date(ws);dd.setDate(ws.getDate()+i);cols.push({ds:dStr(dd.getFullYear(),dd.getMonth(),dd.getDate()),d:dd.getDate(),dow:['日','月','火','水','木','金','土'][i]});}var HOURS=[];for(var h=6;h<=22;h++)HOURS.push(h);var html='<div class="wk-grid"><div class="wk-head"></div>';cols.forEach(function(c){html+='<div class="wk-head'+(c.ds===todStr?' tc':'')+'">'+(c.ds===todStr?'<b>':'')+c.dow+' '+c.d+(c.ds===todStr?'</b>':'')+'</div>';});HOURS.forEach(function(h){html+='<div class="wk-hlbl">'+p2(h)+'</div>';cols.forEach(function(c){var evs=evsOn(c.ds).filter(function(e){return e.start&&parseInt(e.start.split(':')[0])===h});var eh=evs.map(function(e){return'<div class="wk-ev ec'+e.color+'" onclick="openCalEv(\''+e.id+'\',event)">'+esc(e.start)+' '+esc(e.title)+'</div>';}).join('');html+='<div class="wk-cell" onclick="openNewEv(\''+c.ds+'\',event)">'+eh+'</div>';});});return html+'</div>';}
function openNewEv(ds,ev){if(ev)ev.stopPropagation();S.calEditId=null;S.calEditDate=ds;document.getElementById('calModalTitle').textContent=ds+' に予定を追加';document.getElementById('evTitle').value='';document.getElementById('evStart').value='09:00';document.getElementById('evEnd').value='10:00';document.getElementById('evNote').value='';document.getElementById('evDelBtn').style.display='none';S.evColor=0;buildCPicker();refreshEvBookSelect();document.getElementById('calOverlay').classList.add('on');}
function openCalEv(id,ev){if(ev)ev.stopPropagation();var e=S.events.find(function(x){return x.id===id});if(!e)return;S.calEditId=id;S.calEditDate=e.date;document.getElementById('calModalTitle').textContent=e.date+' の予定を編集';document.getElementById('evTitle').value=e.title;document.getElementById('evStart').value=e.start||'09:00';document.getElementById('evEnd').value=e.end||'10:00';document.getElementById('evNote').value=e.note||'';document.getElementById('evDelBtn').style.display='';S.evColor=e.color||0;buildCPicker();refreshEvBookSelect(e.bookId);document.getElementById('calOverlay').classList.add('on');}
function refreshEvBookSelect(sel){document.getElementById('evBook').innerHTML='<option value="">タグなし</option>'+S.books.map(function(b){return'<option value="'+b.id+'"'+(sel===b.id?' selected':'')+'>'+esc(b.title)+'</option>'}).join('')+blBooks.map(function(b){return'<option value="bl_'+b.id+'"'+(sel==='bl_'+b.id?' selected':'')+'>'+esc(b.title)+'</option>'}).join('');}
function saveEvent(){var title=document.getElementById('evTitle').value.trim();if(!title){alert('タイトルを入力してください');return}var ev={id:S.calEditId||uid(),date:S.calEditDate,title:title,start:document.getElementById('evStart').value,end:document.getElementById('evEnd').value,bookId:document.getElementById('evBook').value||null,note:document.getElementById('evNote').value.trim(),color:S.evColor};if(S.calEditId)S.events=S.events.map(function(e){return e.id===S.calEditId?ev:e});else S.events.push(ev);save();closeCalModal();renderCal();}
function deleteEvent(){if(!S.calEditId)return;if(!confirm('削除しますか？'))return;S.events=S.events.filter(function(e){return e.id!==S.calEditId});save();closeCalModal();renderCal()}
function closeCalModal(){document.getElementById('calOverlay').classList.remove('on')}

// ────────────────────────────────────────
